// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entities/user_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7780573664962685596),
    name: 'UserEntity',
    lastPropertyId: const obx_int.IdUid(16, 3428765833145641366),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 854683695191930618),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7544298695757463036),
        name: 'id',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 6385663453030780933),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4557026159293183610),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8020216890117256428),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4115797788444623288),
        name: 'created',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8205764523610310818),
        name: 'updated',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 745437973107337822),
        name: 'avatar',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5347105035037516494),
        name: 'iri',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7893614394671506312),
        name: 'preferredUsername',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7065438667653102047),
        name: 'serverUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2866207440067158385),
        name: 'actorId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8180888277546441967),
        name: 'collectionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3428765833145641366),
        name: 'collectionName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 7780573664962685596),
    lastIndexId: const obx_int.IdUid(1, 6385663453030780933),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1147012112998304753,
      3896929027028370202,
      1409733009498121897,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    UserEntity: obx_int.EntityDefinition<UserEntity>(
      model: _entities[0],
      toOneRelations: (UserEntity object) => [],
      toManyRelations: (UserEntity object) => {},
      getId: (UserEntity object) => object.obxId,
      setId: (UserEntity object, int id) {
        object.obxId = id;
      },
      objectToFB: (UserEntity object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final usernameOffset = fbb.writeString(object.username);
        final emailOffset = fbb.writeString(object.email);
        final createdOffset = fbb.writeString(object.created);
        final updatedOffset = fbb.writeString(object.updated);
        final avatarOffset = object.avatar == null
            ? null
            : fbb.writeString(object.avatar!);
        final iriOffset = fbb.writeString(object.iri);
        final preferredUsernameOffset = fbb.writeString(
          object.preferredUsername,
        );
        final serverUrlOffset = fbb.writeString(object.serverUrl);
        final actorIdOffset = fbb.writeString(object.actorId);
        final collectionIdOffset = fbb.writeString(object.collectionId);
        final collectionNameOffset = fbb.writeString(object.collectionName);
        fbb.startTable(17);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, usernameOffset);
        fbb.addOffset(3, emailOffset);
        fbb.addOffset(6, createdOffset);
        fbb.addOffset(7, updatedOffset);
        fbb.addOffset(8, avatarOffset);
        fbb.addOffset(9, iriOffset);
        fbb.addOffset(10, preferredUsernameOffset);
        fbb.addOffset(12, serverUrlOffset);
        fbb.addOffset(13, actorIdOffset);
        fbb.addOffset(14, collectionIdOffset);
        fbb.addOffset(15, collectionNameOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final collectionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final collectionNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final actorIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final usernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final preferredUsernameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final iriParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final serverUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final createdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final updatedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final avatarParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final object = UserEntity(
          id: idParam,
          collectionId: collectionIdParam,
          collectionName: collectionNameParam,
          actorId: actorIdParam,
          username: usernameParam,
          preferredUsername: preferredUsernameParam,
          email: emailParam,
          iri: iriParam,
          serverUrl: serverUrlParam,
          created: createdParam,
          updated: updatedParam,
          avatar: avatarParam,
        )..obxId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [UserEntity] entity fields to define ObjectBox queries.
class UserEntity_ {
  /// See [UserEntity.obxId].
  static final obxId = obx.QueryIntegerProperty<UserEntity>(
    _entities[0].properties[0],
  );

  /// See [UserEntity.id].
  static final id = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[1],
  );

  /// See [UserEntity.username].
  static final username = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[2],
  );

  /// See [UserEntity.email].
  static final email = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[3],
  );

  /// See [UserEntity.created].
  static final created = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[4],
  );

  /// See [UserEntity.updated].
  static final updated = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[5],
  );

  /// See [UserEntity.avatar].
  static final avatar = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[6],
  );

  /// See [UserEntity.iri].
  static final iri = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[7],
  );

  /// See [UserEntity.preferredUsername].
  static final preferredUsername = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[8],
  );

  /// See [UserEntity.serverUrl].
  static final serverUrl = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[9],
  );

  /// See [UserEntity.actorId].
  static final actorId = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[10],
  );

  /// See [UserEntity.collectionId].
  static final collectionId = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[11],
  );

  /// See [UserEntity.collectionName].
  static final collectionName = obx.QueryStringProperty<UserEntity>(
    _entities[0].properties[12],
  );
}
