version: "2"
run:
  go: "1.25"
linters:
  default: standard
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(pocketbase)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$