name: Go

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'db/**'
  pull_request:
    paths:
      - '.github/**'
      - 'db/**'

jobs:
  db-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with: { go-version-file: go.mod }

      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $HOME/go/bin v2.8.0

      - name: fmt
        run: golangci-lint fmt ./...
        working-directory: db

      - name: check fmt
        run: git diff --exit-code
        working-directory: db

      - name: go vet
        run: go vet ./...
        working-directory: db

      - name: golangci-lint
        run: golangci-lint run --verbose --show-stats ./...
        working-directory: db

      - name: go test
        run: go test ./...
        working-directory: db