name: Web CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'web/**'
  pull_request:
    paths:
      - '.github/**'
      - 'web/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '22'

      - run: go build -o pocketbase_amd64
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
        working-directory: db

        # Build db image
      - run: docker buildx build db/ --no-cache -t flomp/wanderer-db:latest

        # Build web image
      - run: docker buildx build web/ --no-cache -t flomp/wanderer-web:latest

      - run: docker compose up -d
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run: npm run check
      - run: npm run test
